openapi: 3.1.0
info:
  title: A2Pay API
  description: |-
    API supporting payment initation and authorization using the European Digital Identity Wallet.
  version: 0.0.1
externalDocs:
  description: Find out more on GitHub
  url: https://github.com/nobid-consortium/payment-reference-documentation
servers:
  - url: https://bank.example.com
tags:
  - name: payment initiation
    description: Payment Initiation
paths:
  /payment-initiation/{id}:
    post:
      tags:
        - payment initiation
      summary: Post a payment request that has been authorized through the wallet.
      operationId: initPaymentAuth
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the issued A2Pay.
      requestBody:
        description: Payment initiation request
        content:
          application/x-www-form-urlencoded:
            schema:
              type: "string"
        required: true
      responses:
        '200':
          description:  Payment request received.
          content:
            application/json:
              schema:
                type: object
                properties:
                  redirect_uri:
                    type: string
                    examples:
                      - "https://bank.example.org/payment-status/id=091535f699ea575c7937fa5f0f454aee"
  /payment-status/{id}:
    get:
      tags:
        - payment status
      summary: Query the status of a payment.
      operationId: paymentStatus
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the payment as given in the response to the payment initiation request. 
      responses:
        '200':
          description: Payment status code
          content:
            application/json: 
              schema: 
                type: "object"
                properties: 
                  status-code:
                   type: "string"
                   summary: "ISO 20022 payment status code"
                   examples: 
                     - "ACSC"
                     - "RJCT"